# CMake generated Testfile for 
# Source directory: /nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test
# Build directory: /nfs/stak/users/lamad/imc_phd/new_branson/branson/build_dir/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_buffer_1pe "/usr/lib64/mpich-3.2/bin/mpiexec" "-n" "1" "-bind-to" "none" "/nfs/stak/users/lamad/imc_phd/new_branson/branson/build_dir/test/test_buffer_exe")
set_tests_properties(test_buffer_1pe PROPERTIES  PROCESSORS "1" _BACKTRACE_TRIPLES "/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;55;add_test;/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;79;add_branson_test;/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;0;")
add_test(test_cell_1pe "/usr/lib64/mpich-3.2/bin/mpiexec" "-n" "1" "-bind-to" "none" "/nfs/stak/users/lamad/imc_phd/new_branson/branson/build_dir/test/test_cell_exe")
set_tests_properties(test_cell_1pe PROPERTIES  PROCESSORS "1" _BACKTRACE_TRIPLES "/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;55;add_test;/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;79;add_branson_test;/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;0;")
add_test(test_proto_cell_1pe "/usr/lib64/mpich-3.2/bin/mpiexec" "-n" "1" "-bind-to" "none" "/nfs/stak/users/lamad/imc_phd/new_branson/branson/build_dir/test/test_proto_cell_exe")
set_tests_properties(test_proto_cell_1pe PROPERTIES  PROCESSORS "1" _BACKTRACE_TRIPLES "/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;55;add_test;/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;79;add_branson_test;/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;0;")
add_test(test_counter_rng_1pe "/usr/lib64/mpich-3.2/bin/mpiexec" "-n" "1" "-bind-to" "none" "/nfs/stak/users/lamad/imc_phd/new_branson/branson/build_dir/test/test_counter_rng_exe")
set_tests_properties(test_counter_rng_1pe PROPERTIES  PROCESSORS "1" _BACKTRACE_TRIPLES "/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;55;add_test;/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;79;add_branson_test;/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;0;")
add_test(test_input_1pe "/usr/lib64/mpich-3.2/bin/mpiexec" "-n" "1" "-bind-to" "none" "/nfs/stak/users/lamad/imc_phd/new_branson/branson/build_dir/test/test_input_exe")
set_tests_properties(test_input_1pe PROPERTIES  PROCESSORS "1" _BACKTRACE_TRIPLES "/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;55;add_test;/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;79;add_branson_test;/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;0;")
add_test(test_mesh_1pe "/usr/lib64/mpich-3.2/bin/mpiexec" "-n" "1" "-bind-to" "none" "/nfs/stak/users/lamad/imc_phd/new_branson/branson/build_dir/test/test_mesh_exe")
set_tests_properties(test_mesh_1pe PROPERTIES  PROCESSORS "1" _BACKTRACE_TRIPLES "/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;55;add_test;/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;79;add_branson_test;/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;0;")
add_test(test_mpi_types_1pe "/usr/lib64/mpich-3.2/bin/mpiexec" "-n" "1" "-bind-to" "none" "/nfs/stak/users/lamad/imc_phd/new_branson/branson/build_dir/test/test_mpi_types_exe")
set_tests_properties(test_mpi_types_1pe PROPERTIES  PROCESSORS "1" _BACKTRACE_TRIPLES "/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;55;add_test;/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;79;add_branson_test;/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;0;")
add_test(test_photon_1pe "/usr/lib64/mpich-3.2/bin/mpiexec" "-n" "1" "-bind-to" "none" "/nfs/stak/users/lamad/imc_phd/new_branson/branson/build_dir/test/test_photon_exe")
set_tests_properties(test_photon_1pe PROPERTIES  PROCESSORS "1" _BACKTRACE_TRIPLES "/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;55;add_test;/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;79;add_branson_test;/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;0;")
add_test(test_work_packet_1pe "/usr/lib64/mpich-3.2/bin/mpiexec" "-n" "1" "-bind-to" "none" "/nfs/stak/users/lamad/imc_phd/new_branson/branson/build_dir/test/test_work_packet_exe")
set_tests_properties(test_work_packet_1pe PROPERTIES  PROCESSORS "1" _BACKTRACE_TRIPLES "/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;55;add_test;/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;79;add_branson_test;/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;0;")
add_test(test_load_balance_4pe "/usr/lib64/mpich-3.2/bin/mpiexec" "-n" "4" "-bind-to" "none" "/nfs/stak/users/lamad/imc_phd/new_branson/branson/build_dir/test/test_load_balance_exe")
set_tests_properties(test_load_balance_4pe PROPERTIES  PROCESSORS "4" _BACKTRACE_TRIPLES "/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;55;add_test;/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;85;add_branson_test;/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;0;")
add_test(test_imc_state_2pe "/usr/lib64/mpich-3.2/bin/mpiexec" "-n" "2" "-bind-to" "none" "/nfs/stak/users/lamad/imc_phd/new_branson/branson/build_dir/test/test_imc_state_exe")
set_tests_properties(test_imc_state_2pe PROPERTIES  PROCESSORS "2" _BACKTRACE_TRIPLES "/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;55;add_test;/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;86;add_branson_test;/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;0;")
add_test(test_remap_census_8pe "/usr/lib64/mpich-3.2/bin/mpiexec" "-n" "8" "-bind-to" "none" "/nfs/stak/users/lamad/imc_phd/new_branson/branson/build_dir/test/test_remap_census_exe")
set_tests_properties(test_remap_census_8pe PROPERTIES  PROCESSORS "8" _BACKTRACE_TRIPLES "/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;55;add_test;/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;90;add_branson_test;/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;0;")
add_test(test_tally_manager_8pe "/usr/lib64/mpich-3.2/bin/mpiexec" "-n" "8" "-bind-to" "none" "/nfs/stak/users/lamad/imc_phd/new_branson/branson/build_dir/test/test_tally_manager_exe")
set_tests_properties(test_tally_manager_8pe PROPERTIES  PROCESSORS "8" _BACKTRACE_TRIPLES "/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;55;add_test;/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;91;add_branson_test;/nfs/stak/users/lamad/imc_phd/new_branson/branson/src/test/CMakeLists.txt;0;")
